name: Build Single Extension

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build_single:
    name: Build HiAnime extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Prepare signing key
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > signingkey.jks

      - name: Build HiAnime extension
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: chmod +x ./gradlew && ./gradlew :src:en:zoro:assembleRelease

      - name: Clean up CI files
        run: rm signingkey.jks

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: "hianime-apk"
          path: "src/en/zoro/build/outputs/apk/debug/*.apk"
          retention-days: 7
